### ISSUE TITLE
[feature request] mixed slabs

### ISSUE THREAD

**Issue by rmobis** [Eilux/BetterSlabs#11]
It would be cool to be able to mix slabs of different types on the same "block". I'm not sure of the implementation details, but this mod does it for Forge: https://github.com/CJMinecraft01/DoubleSlabs

![image](https://user-images.githubusercontent.com/2119933/100421027-55403200-3066-11eb-86ce-214dc8e10bfd.png)

If you think it makes sense to add this feature, I'd be willing to take a deeper look and probably draw a PR.

**Comment by RDKRACZ** [comment]
Oh this would be nice.

**Comment by rmobis** [comment]
Closing as the project seems to be abandoned
