### ISSUE TITLE
Mod doesn't agree with servers

### ISSUE THREAD

**Issue by icantgetintomyregularaccount** [Eilux/BetterSlabs#13]
Me and my friends have a realm, and when I joined this realm I was greeted with random blocks in random spots or replacing other blocks randomly. It only replaces them client side, so you have to use the right tool for whatever it looks like but it drops whatever should be there. I have a few screenshots just to show.

These rods of pink and lime glazed terracotta are supposed to be bamboo, and the red sandstone stairs are mossy cobble stairs
![2020-12-14_19 15 05](https://user-images.githubusercontent.com/76019806/102153053-57670680-3e44-11eb-8699-6ea6983bf323.png)

This chunk of gray glazed is literally nothing, it is covering the water for my sugar cane
![2020-12-14_19 15 20](https://user-images.githubusercontent.com/76019806/102153081-65b52280-3e44-11eb-8cdf-88833199c3a3.png)

This is inside of one of my friends' house. Wanted to make sure it wasn't just where I loaded in.
![2020-12-14_19 16 43](https://user-images.githubusercontent.com/76019806/102153212-b3318f80-3e44-11eb-9499-1df3a2dfe675.png)

I also wanted to make sure it wasn't just realms so I joined everyone's favorite server Hypixel and sure enough.
![2020-12-14_19 18 06](https://user-images.githubusercontent.com/76019806/102153287-e411c480-3e44-11eb-8991-4c6455eb253b.png)
![2020-12-14_19 17 47](https://user-images.githubusercontent.com/76019806/102153305-e8d67880-3e44-11eb-89dd-ba691eece4d7.png)

Now obviously I didn't expect these mods to work on the server. I just didn't think it would do... whatever... this is, so I didn't disable it. Figured I'd bring it to your attention.

**Comment by Eilux** [comment]
If the server doesn't have the mod installed it will do this due to how I add the additional slab blockstates, so if playing on a vanilla server you can't use the mod very well
