### ISSUE TITLE
RedPower2-like placement behavior

### ISSUE THREAD

**Issue by copygirl** [Eilux/BetterSlabs#3]
Having slabs be placed against the clicked block face and switching with a key really limits how quickly one can build with slabs and doesn't feel intuitive. I was wondering whether you could implement an alternative placement behavior similar to what some other mods have done.

![Screenshot](https://i.imgur.com/zhlRmsg.png)
(Sorry could not find a better picture.)

Depending which area of the selection you click, it would place either place against the block (center) or perpendicular to it (sides).

**Comment by Eilux** [comment]
I don't see how this would be significantly different from current behavior besides having a different visual appearance when placing, I have not used the mod in question but what you are describing sounds similar to the already existing placement modes.

**Comment by copygirl** [comment]
The difference is that one does not have to switch placement modes (taking up a keybind) to place slabs in all configurations.

**Comment by Eilux** [comment]
I think I will keep things how they are for now
