### ISSUE TITLE
Crash upon loading

### ISSUE THREAD

**Issue by Hugman76** [Eilux/BetterSlabs#5]
Log is [here](https://paste.ee/p/UXUXJ)

**Comment by Eilux** [comment]
these are your mods correct? if so I have a few questions

**Comment by Hugman76** [comment]
Yup they are

**Comment by Hugman76** [comment]
The issue might be related to Statement, because the error looks like a config error and only the Statement library has a config file in your mod

**Comment by Eilux** [comment]
Ok when I try adding your api to the build.gradle (I am doing so using jitpack) for testing reasons it crashes with the error `Namespace (intermediary) does not match the current runtime namespace (named)` any idea why this might be happening?

**Comment by Eilux** [comment]
after trying some more things I found that adding your mod's dependencies into my build.gradle made it work

**Comment by Hugman76** [comment]
Yeah this specific issue is bothering me too but I have no idea what's going on with that

**Comment by vinnyg0621** [comment]
I have the same problem

**Comment by Eilux** [comment]
fixed with new release
