### ISSUE TITLE
Crash with BetterNether / BetterEnd

### ISSUE THREAD

**Issue by cs127** [Eilux/BetterSlabs#7]
The mod crashes if [BetterNether](https://github.com/paulevsGitch/BetterNether) or [BetterEnd](https://github.com/paulevsGitch/BetterEnd) is installed.

BetterNether crash report: [crash-2020-10-23_22.18.35-client.txt](https://github.com/Eilux/BetterSlabs/files/5432546/crash-2020-10-23_22.18.35-client.txt)
BetterEnd crash report: [crash-2020-10-23_22.20.23-client.txt](https://github.com/Eilux/BetterSlabs/files/5432547/crash-2020-10-23_22.20.23-client.txt)

**Comment by tvanprooyen** [comment]
A user posted an issue on MoreBlocksMod issues. It crashes minecraft as it loads the client. Keep in mind that its in speculation. Thought it would help. Thanks!

https://github.com/tvanprooyen/mbm/issues/2

**Comment by Eilux** [comment]
yeah this crash has been investigated and should be fixed in the next patch

**Comment by Eilux** [comment]
fixed with new release
