### ISSUE TITLE
Crash on client load

### ISSUE THREAD

**Issue by JuergenSchT** [Eilux/BetterSlabs#8]
[LINK](https://paste.ee/p/G8udG)
The crash might be related to mod conflicts, but I'm not sure about that (e.g. disabling Blockus in the mod list above does not cause a crash when loading the client; but installing Blockus, BetterSlabs on a separate instance with nothing else but Fabric API, OpenJ9compat, Lithium, Phosphor and Sodium does not cause a crash either). To add to the confusion, my complete modpack works just fine on a dedicated server, with no crashes.
I wish I had more time to experiment, but I will be very busy this week.

**Comment by Eilux** [comment]
I checked the crash and it seems to be the same error as the BetterNether crash
